version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: the_musicians_path
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/the_musicians_path -schemas=public -user=postgres
      -password=password -connectRetries=5 migrate
    volumes:
      - ./database:/flyway/sql
    depends_on:
      - db
  backend:
    profiles: ["dev"]
    build:
      context: ./api
      dockerfile: Dockerfile.local
    volumes:
      - ./api:/app
    ports:
      - 3001:3001
    depends_on:
      - flyway
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/the_musicians_path?schema=public"
volumes:
  db:
